"""
Pinterest Client
"""
from pinterest.generated.client.configuration import Configuration
from pinterest.generated.client.api_client import ApiClient
from pinterest.config import PINTEREST_ACCESS_TOKEN
from pinterest.config import PINTEREST_REFRESH_ACCESS_TOKEN
from pinterest.config import PINTEREST_APP_ID
from pinterest.config import PINTEREST_APP_SECRET
from pinterest.config import PINTEREST_API_URI
from pinterest.config import PINTEREST_DEBUG
from pinterest.config import PINTEREST_LOG_FILE
from pinterest.config import PINTEREST_LOGGER_FORMAT
from pinterest.utils.refresh_access_token import get_new_access_token

__all__ = ['default_sdk_client', 'PinterestSDKClient']


class PinterestSDKClient(ApiClient):
    """
    Wrapper API client for SDK high level models

    NOTE: This class is base in a generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech
    """


if not PINTEREST_ACCESS_TOKEN:
    PINTEREST_ACCESS_TOKEN = get_new_access_token(
        app_id=PINTEREST_APP_ID,
        app_secret=PINTEREST_APP_SECRET,
        refresh_access_token=PINTEREST_REFRESH_ACCESS_TOKEN,
        host=PINTEREST_API_URI,
    )

config = Configuration(
    access_token=PINTEREST_ACCESS_TOKEN,
    host=PINTEREST_API_URI,
)

config.debug = PINTEREST_DEBUG
config.logger_file = PINTEREST_LOG_FILE
config.logger_format = PINTEREST_LOGGER_FORMAT

default_sdk_client = PinterestSDKClient(configuration=config)
