openapi: 3.0.3
info:
  version: 0.1.4
  title: Pinterest Python SDK
  description: Pinterest SDK for Python
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
    email: pinterest-api@pinterest.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
  - url: https://api.pinterest.com/v5
paths:
  /test:
    get:
      summary: Arbitrate summary
      description: This is an arbitrate endpoint, please visit https://developers.pinterest.com/docs/api/v5/ for more information
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
