name: Publish Test

on: [pull_request]

jobs:
  build:
    environment: integ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run publish pypi test
        env:
          TWINE_USERNAME: ${{ secrets.CI_USERNAME_TEST_PYPI }}
          TWINE_PASSWORD: ${{ secrets.CI_PASSWORD_TEST_PYPI }}
        run: |
          python -m pip install --upgrade pip
          make publish_pypi_test
